name: C/C++ CI

on:
  workflow_dispatch:
env:
  SSH_ACTIONS: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#     - name: update
#       run: ./scripts/feeds update -a
#     - name: install
#       run: ./scripts/feeds install -a
#     - name: conf
      #uses: P3TERX/debugger-action@main
      #if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
      #run: make menuconfig
#       run: make defconfig
#     - name: mkdl
#       run: make -j8 download

    - name: Prepare artifact
      run: |
          #mkdir -p ../artifact/code
          #cp -rf ./* ../artifact/code
          pwd
    - name: Deliver buildinfo
      uses: actions/upload-artifact@v2
      with:
          name: OpenWrt_buildinfo
          path: ./artifact/code/

